os: linux
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y # For g++-4.9
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo apt-get install -y libgmp-dev libssl-dev libgtest-dev libboost libcrypto++-dev libboost-program-options-dev

script:
  - LIBSNARK_FLAGS="NO_PROCPS=1 NO_GTEST=1 NO_DOCS=1 STATIC=1" ./get-libsnark
  - NO_PROCPS=1 MINDEPS=1 make
  - ./zerocash_pour_ppzksnark/tests/test_zerocash_pour_ppzksnark
